#!/usr/bin/env python

import rospy
import sendgoal_node
import tadashi_helpers as th
import socket
from move_base_msgs.msg import MoveBaseGoal

def receivegoal():
    rospy.init_node('receivegoal_node', anonymous=True)

    localIP = 'localhost'   # I don't think you set this, but if failure set to '' or '127.0.0.1' 
                            # or '192.168.105.x' as shown in ifconfig

    localPort = 20001
    bufferSize = 1024

    # msgFromServer = "1"
    # bytesToSend = str.encode(msgFromServer)

    UDPServerSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)
    UDPServerSocket.bind((localIP, localPort))

    print('UDP server up and listening')

    actionclient = sendgoal_node.Client()

    while(True):
        bytesAddressPair = UDPServerSocket.recvfrom(bufferSize)

        commands = th.splitstringbychar(bytesAddressPair[0], ' ')
        address = bytesAddressPair[1]

        command = commands[0]
        args = commands[1:]

        target = MoveBaseGoal()
        target.target_pose.header.frame_id = "base_link"
        target.target_pose.header.stamp = rospy.Time.now()

        if int(args[0]) == 1:
            target.target_pose.pose.position.x = -3.0
            target.target_pose.pose.position.y = 1.0
            target.target_pose.pose.orientation.w = 1.0
        elif int(args[0]) == 2:
            target.target_pose.pose.position.x = -3.0
            target.target_pose.pose.position.y = 1.0
            target.target_pose.pose.orientation.w = 1.0
        
        actionclient.sendGoal(target)

        print('Message from Client:{}'.format(bytesAddressPair[0]))
        print('Client IP Address:{}'.format(address))

        # address = (address[0], 20002)
        # UDPServerSocket.sendto(bytesToSend, address)

        # GOTO 1 or GOTO 2

    rospy.spin()


if __name__ == '__main__':
    receivegoal()